### ISSUE TITLE
Minor error in shell script creation

### ISSUE THREAD

**Issue by zkstewart** [ruanjue/wtdbg-1.2.8#1]
Hi,

Would like to say firstly that I've been trying basically every assembler I can find for my genome, and so far SMARTdenovo has given one of the best assemblies from initial statistics, so I'm very interested in the development of SMARTdenovo and/or this wtdbg assembler!

On topic: When running run_wtdbg_assembly.sh with "-T > sub_script.sh", the output script has a typo which causes an error in the first uncommented line (--rescure-low-cov-edges). Manually editing this line fixes the issue.

I'll let you know how the assembly goes, unsure exactly how long it should take with the resources I have available.

Zac.

**Comment by ruanjue** [comment]
Hi Zac, thanks for your comments.
Yes, there is a typo. I have fixed it. Thanks! 
Hope to hear the assembly from you.
