### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fantasticair** [ruanjue/wtdbg-1.2.8#10]
Hi,
I reported the ‘warning: assignment makes pointer from integer without a cast’ error when installing the software. How to solve it?

**Comment by ruanjue** [comment]
Hi, 
Please tell me the location of this warning, includes File_Name:Line_Number.

Best

**Comment by fantasticair** [comment]
Thanks,
I have solved it because the gcc version is too low.

**Comment by ruanjue** [comment]
Great.
