### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by njaupan** [ruanjue/wtdbg-1.2.8#11]
Dear Ruanjue,

I tried many times to install, but failed. I paste the command here, could you help me to check?

$git clone https://github.com/ruanjue/wtdbg-1.2.8.git
$cd wtdbg-1.2.8
~/wtdbg-1.2.8$ make
The error report is attached in the file. 
[wtdbg_install_error.txt](https://github.com/ruanjue/wtdbg-1.2.8/files/2200967/wtdbg_install_error.txt)

Best,
panpan

**Comment by ruanjue** [comment]
Hi panpan,

Maybe the errors were caused by `date` command in your PC. There was a comma in "mardi 17 juillet 2018, 10:57:40 (UTC+0200)",  please type this command to compile it again.
```
gcc -g3 -W -Wno-unused-but-set-variable -O4 -DTIMESTAMP="mardi 17 juillet 2018 10:57:40 (UTC+0200)" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o wtdbg-1.2.8 wtdbg.c -lm -lrt -lpthread
```
Please let me know whether it works! 
Thanks,
Jue

**Comment by njaupan** [comment]
Dear Ruanjue,

It works now and I close this issue, thank you!

Best,
panpan
