### ISSUE TITLE
Error-free sequences file

### ISSUE THREAD

**Issue by evanrrees** [ruanjue/wtdbg-1.2.8#13]
I see wtdbg-1.2.8 has the parameter `-I <string> Error-free sequences file, +`. Can paired-end illumina reads in fastq format be passed as an argument (in addition to nanopore sequences passed to `-i`)?

**Comment by ruanjue** [comment]
`-I` accepts error-free contigs. wtdbg prefer to select verticles from those sequences. In older version, wtdbg try hybrid assembly using Illumina contigs and long noisy reads. Now, I haven't touched this parameter for a long time, not sure whether it still works.

Best,
Jue

**Comment by evanrrees** [comment]
Great, thank you for clarifying! If I encounter any issues using this parameter I will let you know.
The speed of wtdbg is impressive, I am working on tuning to improve contiguity and completeness (BUSCO).

Thanks,
Evan
