### ISSUE TITLE
I want to change the parameter --edge-min 2 but don't want to rerun the alignment again, is it possible ?

### ISSUE THREAD

**Issue by orangeSi** [ruanjue/wtdbg-1.2.8#4]
Hi,
  After my first run is done,  I want to change the parameter --edge-min 2 but don't want to rerun the alignment again, is it possible ?

Thanks~

**Comment by ruanjue** [comment]
Yes, you can tune parameters by re-using the alignments.
`--edge-min 2 --load-alignments <previous_aligments like dbg.alignments>`

**Comment by ruanjue** [comment]
Or re-using the nodes will be faster than re-using alignments
`--edge-min 2 --load-clips <dbg.clps> --load-nodes <dbg.1.nodes>`

**Comment by orangeSi** [comment]
thanks~
