### ISSUE TITLE
Is it necessary to further run consensus tools on the results of wtdbg or smartdenovo?

### ISSUE THREAD

**Issue by YiweiNiu** [ruanjue/wtdbg-1.2.8#5]
Hi Jue,

I'm sorry to bother you once anain.

I found a evaluation [paper](https://www.ncbi.nlm.nih.gov/pubmed/?term=29112696) and it says (paragraph 11 of "Discussion"):
>...Wtdbg assemblies, which always ranked last, mostly because no consensus procedure was executed, would need additional rounds of consensus polishing to effectively compete with other assemblers. 

So I'm wondering that if it is necessary to further run consensus tools after running `wtdbg1.1.006`, `wtdbg1.2.8` and `smartdenovo` **now**, such as [Racon](https://github.com/isovic/racon)? I know all three tools have consensus modules, and have been updated since this paper was published.

I'm working on a *de novo* genome assemlby project and there are very limited genomic resources to evaluate the correctness. Except PacBio data, I also have several short reads libraries, so I want to perform scaffolding based on results of `wtdbg`. I don't know how the errors in contigs affect the scaffolding.

Any suggestions or thoughts would be appreciated. Thank you!

Bests,
Yiwei Niu

**Comment by ruanjue** [comment]
Thanks for interesting.

The inside consensus tool `wtdbg-cns` aims to provide a quick way to reduce sequencing errors. It is suggested to use Quiver and/or Pilon to polish the consensus sequences after you feel happy with the assembly. Usually, `wtdbg-cns` can reduce error rate down to less than 1%, which can be well-aligned by short reads.

BTW, the paper used strage parameters for wtdbg, limited to say wtdbg always ranked last, I had emailed the author just after its publish.

**Comment by ruanjue** [comment]
Have a good luck!
