### ISSUE TITLE
cannot find reads

### ISSUE THREAD

**Issue by tangerzhang** [ruanjue/wtdbg-1.2.8#9]
Dear Jue,
Could you please indicate me how to solve this problem?
Thanks!

[Tue Jun 26 17:19:15 2018] loading reads
8071186 reads
[Tue Jun 26 17:28:34 2018] Done, 8071186 reads, 149999992485 bp, 581944848 bins
** PROC_STAT(0) **: real 559.139 sec, user 484.810 sec, sys 149.680 sec, maxrss 44491600.0 kB, maxvsize 157162940.0 kB
[Tue Jun 26 17:28:34 2018] loading alignments from "1-1.kbmap","1-2.kbmap","1-3.kbmap","1-4.kbmap","1-5.kbmap","1-6.kbmap","1-7.kbmap","1-8.kbmap","1-9.kbmap","1-10.kbmap","2-1.kbmap","2-2.kbmap","2-3.kbmap","2-4.kbmap","2-5.kbmap","2-6.kbmap","2-7.kbmap","2-8.kbmap","2-9.kbmap","2-10.kbmap","3-1.kbmap","3-2.kbmap","3-3.kbmap","3-4.kbmap","3-5.kbmap","3-6.kbmap","3-7.kbmap","3-8.kbmap","3-9.kbmap","3-10.kbmap","4-1.kbmap","4-2.kbmap","4-3.kbmap","4-4.kbmap","4-5.kbmap","4-6.kbmap","4-7.kbmap","4-8.kbmap","4-9.kbmap","4-10.kbmap","5-1.kbmap","5-2.kbmap","5-3.kbmap","5-4.kbmap","5-5.kbmap","5-6.kbmap","5-7.kbmap","5-8.kbmap","5-9.kbmap","5-10.kbmap","6-1.kbmap","6-2.kbmap","6-3.kbmap","6-4.kbmap","6-5.kbmap","6-6.kbmap","6-7.kbmap","6-8.kbmap","6-9.kbmap","6-10.kbmap","7-1.kbmap","7-2.kbmap","7-3.kbmap","7-4.kbmap","7-5.kbmap","7-6.kbmap","7-7.kbmap","7-8.kbmap","7-9.kbmap","7-10.kbmap","8-1.kbmap","8-2.kbmap","8-3.kbmap","8-4.kbmap","8-5.kbmap","8-6.kbmap","8-7.kbmap","8-8.kbmap","8-9.kbmap","8-10.kbmap","9-1.kbmap","9-2.kbmap","9-3.kbmap","9-4.kbmap","9-5.kbmap","9-6.kbmap","9-7.kbmap","9-8.kbmap","9-9.kbmap","9-10.kbmap","10-1.kbmap","10-2.kbmap","10-3.kbmap","10-4.kbmap","10-5.kbmap","10-6.kbmap","10-7.kbmap","10-8.kbmap","10-9.kbmap","10-10.kbmap"
62610000 -- Cannot find read "m54173_18030852/49217650/1065_26917" in LINE:62611733 in build_nodes_graph -- wtdbg.c:1034 --
63650000 -- Cannot find read "m54174_180329_082736/7826476/7300_29818" in LINE:63653665 in build_nodes_graph -- wtdbg.c:1034 --
63740000 -- Cannot find read "m54170_180315_1329554172_180322_035319/49480042/167_25553" in LINE:63740153 in build_nodes_graph -- wtdbg.c:1034 --
64370000 -- Cannot find read "m54173_180331_111252/52035731/0_17734929/33292754/0_27797" in LINE:64375142 in build_nodes_graph -- wtdbg.c:1034 --
 -- Cannot find read "-" in LINE:64375513 in build_nodes_graph -- wtdbg.c:1034 --
64460000 -- Cannot find read "+" in LINE:64463256 in build_nodes_graph -- wtdbg.c:1034 --
66190000 -- Cannot find read "m54170_18030256" in LINE:66195795 in build_nodes_graph -- wtdbg.c:1034 --
67290000 -- Cannot find read "m54174_180319_171333/70254672/0_26/0_26562" in LINE:67294315 in build_nodes_graph -- wtdbg.c:1017 --
67940000 -- Cannot find read "m54173_18030_55439" in LINE:67945009 in build_nodes_graph -- wtdbg.c:1017 --
67950000 -- Cannot find read "m54174_180337/17499038/0_26853" in LINE:67957390 in build_nodes_graph -- wtdbg.c:1034 --
79350000 -- Cannot find read "m54173_180322_135952/29_27776" in LINE:79352414 in build_nodes_graph -- wtdbg.c:1034 --
83890000 -- Bad cigar '/' "3Md3m2452677/0_23760" in LINE:83890828 in build_nodes_graph -- wtdbg.c:1072 --

**Comment by ruanjue** [comment]
There is a simple speculation: some kbmap file(s) were incomplete. 

Referring to the first warnning, LINE:62611733 was the line number for all your files in input order. It will help you to locate the problem.

Best,
Jue

**Comment by tangerzhang** [comment]
Redo the alignment solve this problem!
Thanks!
